name: 'Autocoder Bot'
description: 'Generates code from a GitHub issue using OpenAI and creates a pull request.'
author: 'autocoder-bot'

# Define the inputs your action accepts
inputs:
  github_token:
    description: 'The GITHUB_TOKEN to authenticate against the GitHub API.'
    required: true
  openai_api_key:
    description: 'API key for OpenAI to generate code.'
    required: true
  issue_label:
    description: 'The label to add to the created pull request.'
    required: false
    default: 'autocoder-bot'

# Define the outputs your action produces
outputs:
  pull_request_url:
    description: 'The URL of the newly created pull request.'
    value: ${{ steps.create_pr.outputs.pull-request-url }}

# Define the branding (icon and color) for your action in the Marketplace
branding:
  icon: 'code'
  color: 'purple'

# Define the steps to run
runs:
  using: 'composite'
  steps:
    # This step makes the script (part of this action's repo) executable
    - name: Set permissions for script.sh
      run: chmod +x ${{ github.action_path }}/gpt_interaction_script.sh
      shell: bash

    # This step runs the script, passing in inputs and event data
    - name: Run script.sh
      run: ${{ github.action_path }}/gpt_interaction_script.sh "$GH_TOKEN" "$REPO" "$ISSUE_NUM" "$OPENAI_KEY"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        ISSUE_NUM: ${{ github.event.issue.number }}
        OPENAI_KEY: ${{ inputs.openai_api_key }}

    # This step configures Git for the committer
    - name: Configure git
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
      shell: bash

    # This step commits the code and creates the pull request
    - name: Create Pull Request
      id: create_pr # Give this step an ID to access its outputs
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github_token }}
        commit-message: 'feat: Add generated code for issue #${{ github.event.issue.number }}'
        title: 'Autocode: Fixes issue #${{ github.event.issue.number }}'
        body: |
          This PR was auto-generated by the autocoder-bot.
          It addresses issue #${{ github.event.issue.number }}.
        committer: autocoder-bot <actions@github.com>
        author: autocoder-bot <actions@github.com>
        branch: autocoder-branch-${{ github.event.issue.number }}
        base: main
        labels: ${{ inputs.issue_label }}
